---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache
      tags: always
      dnf: update_cache=yes

- hosts: localhost
  become: true
  roles:

    - common       # List of essential packages
    - plasma
    - design       # Design pack
    - comunication
    - browsers
    - dev
    - multimedia
    - virtualization
    - games
    #- libvirt-bridge
    #- gpupt
    #- awesome
    #- lexmark-e120
    #- autofs
