---

- hosts: local
  vars_files:
    - group_vars/all.yml

  roles:

    - common       # List of essential packages
    - users
    - design       # Design pack
    - latex        # Latex and ide texmaker
    - composer
    - nodejs
    - browsers
    - dev
    - multimedia
    - virtualization
   

