---
- name: Virtualization | Install lists packages
  dnf:
    name:
      - virt-manager
      - distrobox
      - podman
      - podman-compose
      - podman-docker
      - libgomp
      - glibc-headers
      - glibc-devel
      - kernel-headers
      - kernel-devel
      - dkms
    state: latest
