---
- name: Restart autofs
  ansible.builtin.service:
    name: "{{ autofs_service_name }}"
    state: restarted

- name: Reload autofs
  ansible.builtin.service:
    name: "{{ autofs_service_name }}"
    state: reloaded
