---
- name: Package | Install lists packages
  dnf:
    name:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-32.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-32.noarch.rpm
      - zsh
      - geary
      - bash-completion
      - openssh-server
      - vim
      - git
      - NetworkManager-tui
      - unar
      - htop
      - tree
      - dstat
      - screen
      - curl
      - wget
      - ccze
      - tmux
      - terminator
      - tig
      - unzip
      - neofetch
      - iotop
      - pciutils
      - usbutils
      - nmap
      - youtube-dl
      - squashfs-tools
      - shntool
      - unrar
      - p7zip
      - mc
      - nnn
      - sshfs
      - gnome-tweak-tool
      - util-linux-user
      - qt5ct
      - yaru-theme
      - ubuntu-title-fonts
      - gnome-shell-extension-netspeed
      - gnome-shell-theme-selene
      - chrome-gnome-shell
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-desktop-icons
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-freon
      - gnome-shell-extension-gamemode
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-media-player-indicator
      - gnome-shell-extension-pomodoro
      - gnome-shell-extension-system-monitor-applet
      - gnome-shell-extension-topicons-plus
      - gnome-shell-theme-yaru
      - libwebp-tools
    state: latest

- name: Install webp thumbnailer
  template:
    src: webp.thumbnailer
    dest: /usr/share/thumbnailers/
    owner: root
    group: root
    mode: '0644'

