---
- name: Package | Install lists packages
  dnf:
    name: python3-dnf
    
- name: Setup SSHD
  service: name=sshd state=started enabled=yes

- name: Install RPMfusion free
  dnf: name=https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-branched.noarch.rpm state=latest disable_gpg_check=yes

- name: Install RPMfusion nonfree
  dnf: name=https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-branched.noarch.rpm state=latest disable_gpg_check=yes

- name: Package | Install lists packages
  dnf:
    name:
      - ImageMagick
      - NetworkManager-tui
      - bash-completion
      - bat
      - btop
      - byobu
      - ccze
      - compsize
      - curl
      - dejavu-fonts-all
      - distrobox
      - dstat
      - fastfetch
      - fira-code-fonts
      - ffmpegthumbnailer
      - ffmpegthumbs
      - flac
      - foliate
      - fortune-mod
      - git
      - gnome-tweak-tool
      - htop
      - iotop
      - jetbrains-mono-fonts-all
      - libreoffice-langpack-pt-BR
      - libwebp-tools
      - mc
      - nix
      - nmap
      - nnn
      - openssh-server
      - p7zip
      - pciutils
      - pdf2djvu
      - poppler-utils
      - powerline-fonts
      - qt5ct
      - screen
      - shntool
      - squashfs-tools
      - sshfs
      - terminator
      - tig
      - tmux
      - tree
      - unar
      - unrar
      - unzip
      - usbutils
      - util-linux-user
      - vim
      - wget
      - xclip
      - yakuake
      - yaru-theme
      - youtube-dl
      - yt-dlp
      - zoxide
      - zsh
      - cockpit
      - cockpit-bridge
      - cockpit-composer
      - cockpit-files
      - cockpit-machines
      - cockpit-podman
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - cockpit-image-builder 
      - cockpit-networkmanager
      
    state: installed

- name: Install webp thumbnailer
  template:
    src: webp.thumbnailer
    dest: /usr/share/thumbnailers/
    owner: root
    group: root
    mode: '0644'

- name: Replace ffmpeg-free
  shell: dnf swap ffmpeg-free ffmpeg --allowerasing -y

- name: Add flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo



- name: Enable cockpit web console
  service:
    name: cockpit.socket
    state: started
    enabled: true

