---
- name: Setup SSHD
  service: name=sshd state=started enabled=yes

- name: Install RPMfusion free
  dnf: name=https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-branched.noarch.rpm state=latest disable_gpg_check=yes

- name: Install RPMfusion nonfree
  dnf: name=https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-branched.noarch.rpm state=latest disable_gpg_check=yes



- name: Package | Install lists packages
  dnf:
    name:
      - zsh
      #- geary
      - bash-completion
      - openssh-server
      - vim
      - git
      - NetworkManager-tui
      - unar
      - htop
      - tree
      - dstat
      - screen
      - curl
      - wget
      - ccze
      - tmux
      - terminator
      - tig
      - unzip
      - neofetch
      - iotop
      - pciutils
      - usbutils
      - nmap
      - youtube-dl
      - squashfs-tools
      - shntool
      - unrar
      - p7zip
      - mc
      - nnn
      - sshfs
      - gnome-tweak-tool
      - util-linux-user
      - qt5ct
      - yaru-theme
      - ubuntu-title-fonts
      #- gnome-shell-extension-netspeed
      #- gnome-shell-theme-selene
      #- chrome-gnome-shell
      #- gnome-shell-extension-appindicator
      #- gnome-shell-extension-desktop-icons
      #- gnome-shell-extension-dash-to-dock
      #- gnome-shell-extension-freon
      #- gnome-shell-extension-gamemode
      #- gnome-shell-extension-gsconnect
      #- gnome-shell-extension-media-player-indicator
      #- gnome-shell-extension-pomodoro
      #- gnome-shell-extension-system-monitor-applet
      #- gnome-shell-extension-topicons-plus
      #- gnome-shell-theme-yaru
      - libwebp-tools
      - pdf2djvu
      - poppler-utils
      - ImageMagick
      - xclip
      - libreoffice-langpack-pt-BR
      - compsize
      - foliate
      - yakuake
      - fortune-mod
      - zsh
      - ffmpegthumbnailer
      - ffmpegthumbs
      
    state: installed

- name: Install webp thumbnailer
  template:
    src: webp.thumbnailer
    dest: /usr/share/thumbnailers/
    owner: root
    group: root
    mode: '0644'

