---
- name: Install "Snap"
  dnf: name=snapd state=latest 

- name: Enable "Snap"
  service: name=snapd state=started enabled=yes

- name: Create "snap" symlink
  file:
    src:  /var/lib/snapd/snap
    dest: /snap
    owner: root
    state: link


- name: Install "phpstorm" with option --classic
  snap:
    name: phpstorm
    classic: yes

- name: Install "goland" with option --classic
  snap:
    name: goland
    classic: yes

- name: Install "webstorm" with option --classic
  snap:
    name: webstorm
    classic: yes

- name: Install "pycharm-professional" with option --classic
  snap:
    name: pycharm-professional
    classic: yes

- name: Install "insomnia" 
  snap:
    name: insomnia

- name: Install "postbird" 
  snap:
    name: postbird        

- name: Add MS keys
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add repository
  yum_repository:
    name: vscode
    description: vscode repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes

- name: VSCode
  dnf: pkg=code state=latest

- name: Install "codeblocks"
  dnf:
    name: codeblocks


- name: Install "anjuta"
  dnf:
    name: anjuta

- name: Install "arduino"
  dnf:
    name: arduino

- name: Install "micro"
  dnf:
    name: micro

- name: Install "zeal"
  dnf:
    name: zeal

- name: Install "zeal"
  dnf:
    name: zeal
