---
- name: Install Dev tools
  dnf:
    name: "@development-tools"
    state: present

- name: Install Dev Stuff
  dnf:
    name:

      - gcc-c++
      - intltool
      - libtool
      - fira-code-fonts
      - cargo
      - nix
      - uv
      - conda
      - python-unversioned-command
      - golang
      - binutils
      - gcc
      - make
      - cmake
      - patch
      
    disable_gpg_check: no
    state: installed

- name: Install "DBeaver"
  flatpak:
    name: io.dbeaver.DBeaverCommunity 
    state: present

- name: Install "Android Studio"
  flatpak:
    name: com.google.AndroidStudio
    state: present


- name: Add MS keys
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add VSCode repository
  yum_repository:
    name: vscode
    description: vscode repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes

- name: VSCode
  dnf: pkg=code state=latest

#- name: Add docker repository
#  yum_repository:
#    name: docker
#    description: docker repo
#    baseurl: https://download.docker.com/linux/fedora/39/x86_64/stable
#    gpgkey: https://download.docker.com/linux/fedora/gpg
#    gpgcheck: true
#    enabled: yes

#- name: Install Docker
#  dnf: 
#    name:
#      - docker-ce
#      - docker-ce-cli
#      - containerd.io
#    state: latest

- name: Install No Machine
  dnf:
    name: https://web9001.nomachine.com/download/9.7/Linux/nomachine_9.7.3_1_x86_64.rpm
    disable_gpg_check: true
    state: present

#- name: Start docker service
# service:
#    name: docker
#    state: started

- name: Install "micro"
  dnf:
    name: micro

- name: Android Tools
  dnf:
    name: android-tools

- name: VSCode
  dnf: pkg=code state=latest

- name: Install Eng Stuff
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.fritzing.Fritzing
    - org.openscad.OpenSCAD
    - com.prusa3d.PrusaSlicer
    - com.ultimaker.cura
