---
- name: Install X11 libs
  dnf:
    name:
      - libX11-devel
      - libXcursor-devel 
      - libXrandr-devel
      - libXinerama-devel
      - libXi-devel
      - mesa-libGL-devel
      - gcc-c++
      - SDL2_gfx-devel
      - SDL2_image-devel
      - SDL2_mixer-devel
      - SDL2_ttf-devel
      - SDL2-devel
      - libXxf86vm-devel
      - intltool
      - glib-devel
      - glib2-devel
      - libtool
      - fira-code-fonts
      - cargo
      - java-1.8.0-openjdk-devel 
    state: installed

- name: Add flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install "Snap"
  dnf: name=snapd state=latest 

- name: Enable "Snap"
  service: name=snapd state=started enabled=yes

- name: Create "snap" symlink
  file:
    src:  /var/lib/snapd/snap
    dest: /snap
    owner: root
    state: link


- name: Install "phpstorm" 
  flatpak:
    name: com.jetbrains.PhpStorm
    state: present

- name: Install "goland" 
  flatpak:
    name: com.jetbrains.Goland
    state: present

- name: Install "clion"                      
  flatpak:
    name: com.jetbrains.Clion
    state: present 

- name: Install "Pycharm-Professional"                      
  flatpak:
    name: com.jetbrains.Pycharm-Professional
    state: present

- name: Install "WebStorm"                      
  flatpak:
    name: com.jetbrains.WebStorm
    state: present

- name: Install "DBeaver"
  flatpak:
    name: io.dbeaver.DBeaverCommunity 
    state: present

- name: Install "Android Studio"
  flatpak:
    name: com.google.AndroidStudio
    state: present


- name: remove "insomnia" 
  snap:
    name: insomnia
    state: present

- name: Install "DBeaver CE" 
  snap:
    name: dbeaver-ce        

- name: Add MS keys
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add repository
  yum_repository:
    name: vscode
    description: vscode repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes

- name: VSCode
  dnf: pkg=code state=latest

- name: Install "codeblocks"
  dnf:
    name: codeblocks

- name: Install "anjuta"
  dnf:
    name: anjuta

- name: Install "arduino"
  dnf:
    name: arduino

- name: Install "micro"
  dnf:
    name: micro

- name: Install "zeal"
  dnf:
    name: zeal

